### PR TITLE
docs: clearer usage

### PR DESCRIPTION
**Pull request by uncenter**
I think selecting a flavor and accent can be one step, and that step can be consolidated into the moving folders/files step as well.

### CODE REVIEW

**Comment by Anomalocaridid** [comment]
Thanks for your contribution!

I am not sure how this clarifies the usage. It certainly makes it more concise, but seemingly at the cost of making it slightly less clear.

For instance, the way it is now makes it clear that you essentially have to go through two layers of directories before getting to individual themes.

However, I am still willing to hear you out if you have further reasoning as to why this change would be worthwhile or if you wanted to try to make further changes to address my criticism.

**Comment by uncenter** [comment]
> For instance, the way it is now makes it clear that you essentially have to go through two layers of directories before getting to individual themes.

This is still abundantly clear in these directions. Before though, it required two separate steps just to tell the user to pick the directory with their flavor + accent combo of choice. That can easily be one. And since copying the files/directory is the *action* here, it makes sense for that clause to be included in the same step as well.

**Comment by Anomalocaridid** [comment]
Fair enough. I think I get what you mean now.

**Comment by Anomalocaridid** [comment]
Thank you!

**Pull request merged**
